test:
  dialect: postgres
  datasource: port=25432 user=zrobank password=password dbname=zrobank sslmode=disable
  dir: migrations
  table: migrations

development:
  dialect: postgres
  datasource: host=localhost user=zrobank port=15432 password=password dbname=zrobank sslmode=disable
  dir: migrations
  table: migrations

homologation:
  dialect: postgres
  datasource: host=$PRD_DB_HOST port=5432 user=$PRD_DB_USER password=$PRD_DB_PASSWORD dbname=$PRD_DB_DBNAME sslmode=disable
  dir: migrations
  table: migrations

production:
  dialect: postgres
  datasource: $DATABASE_URL
  dir: migrations
  table: migrations
